# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39ef77a00d53b778d1e32bfb048e89215ce79e05ab249655d1c69a265236fa3511cfebd704e53f2d7cf2ff7fcad356a8f00dab4f39300fd5549971fc5a185d8c

test:
  secret_key_base: 14aca63da47b64e28d27d455d0c02e962fad1fa6b26fc5a365b4a6b3167cad39a1dc85988fce3d60badf2f378c95169cff60050abe45c3fea79eb7ef62785a9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
